In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_global

## Numpy Arrays, their type and size

In [3]:
l = [i for i in range(0, 21)]

In [4]:
a = np.array(l, dtype=int)

In [5]:
b = np.array(l, dtype=np.int8)

In [6]:
c = np.array(l, dtype=np.int16)

In [7]:
d = np.array(l, dtype=np.int32)

In [8]:
e = np.array(l, dtype=np.int64)

In [9]:
a, b, c, d, e

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20], dtype=int8),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20], dtype=int16),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20], dtype=int32),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20]))

In [18]:
a.size, a.itemsize

(21, 8)

In [17]:
b.size, b.itemsize

(21, 1)

In [14]:
c.size, c.itemsize

(21, 2)

In [15]:
d.size, d.itemsize

(21, 4)

In [16]:
e.size, e.itemsize

(21, 8)

## Array indexing

In [21]:
a[0:4]

array([0, 1, 2, 3])

In [22]:
a[1:11:2]

array([1, 3, 5, 7, 9])

In [23]:
a[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [24]:
a[1::3]

array([ 1,  4,  7, 10, 13, 16, 19])

In [28]:
a[[1,5,8,-1]]

array([ 1,  5,  8, 20])

In [30]:
a[[1:5:, -2, -1]]

SyntaxError: invalid syntax (<ipython-input-30-81a95e224b32>, line 1)

In [31]:
a[[range(1,5)]]

/home/deepa/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


array([1, 2, 3, 4])

In [32]:
a[(range(1,5))]

array([1, 2, 3, 4])

In [33]:
a[(range(1,5), -2, -1)]

IndexError: too many indices for array

In [34]:
a[(range(1,5), -1)]

IndexError: too many indices for array

## Matrices and their shape

In [22]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

In [23]:
a.shape, a.size, a.itemsize, a.ndim

((4, 3), 12, 8, 2)

In [42]:
b = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
    ]
], dtype=np.float32)

In [43]:
b.shape, b.size, b.itemsize, b.ndim

((2, 2, 3), 12, 4, 3)

In [44]:
b

array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]]], dtype=float32)

In [48]:
c = np.array([
        [1, 2, 3],
        [4, 5],
], dtype=np.int32)

ValueError: setting an array element with a sequence.

In [120]:
c = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [7, 8, 9],
        [10, 11, 12],
    ]
])

In [121]:
c.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [124]:
x = np.array([[1.0, 2.0, 3.0, 4.0],
     [5.0, 6.0, 7.0, 8.0]])
y = np.array([[10, 20, 30, 40],
     [50, 60, 70, 80]])

In [128]:
np.hstack((x, y))

array([[ 1.,  2.,  3.,  4., 10., 20., 30., 40.],
       [ 5.,  6.,  7.,  8., 50., 60., 70., 80.]])

In [129]:
np.vstack((x, y))

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [10., 20., 30., 40.],
       [50., 60., 70., 80.]])

In [130]:
np.hstack((b, c))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 4 and the array at index 1 has size 3

In [131]:
t = np.arange(20)
t = t.reshape(4, 5)

In [132]:
print(t)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [134]:
np.hsplit(t, (2, 4))

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16]]),
 array([[ 2,  3],
        [ 7,  8],
        [12, 13],
        [17, 18]]),
 array([[ 4],
        [ 9],
        [14],
        [19]])]

In [133]:
np.hsplit(t, 3)

ValueError: array split does not result in an equal division

In [135]:
np.vsplit(t, 2)

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])]

In [136]:
np.vsplit(t, (1, 3))

[array([[0, 1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19]])]

## Array creation

In [32]:
d = np.array([[1.5, 2, 3, 4], [2, 0, 0, 7]])
d, d.ndim, d.dtype, d.size, d.itemsize, d.shape

(array([[1.5, 2. , 3. , 4. ],
        [2. , 0. , 0. , 7. ]]),
 2,
 dtype('float64'),
 8,
 8,
 (2, 4))

In [33]:
e = np.array([[1, 2], [3, 4]], dtype=complex)
e, e.ndim, e.dtype, e.size, e.itemsize, e.shape

(array([[1.+0.j, 2.+0.j],
        [3.+0.j, 4.+0.j]]),
 2,
 dtype('complex128'),
 4,
 16,
 (2, 2))

In [36]:
game = np.zeros((3, 4), dtype=int)
game

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [38]:
o = np.ones((2, 3, 4))
o

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [39]:
p = np.arange(0, 2, 0.3)
p

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [43]:
q = np.linspace(0, 2 * np.pi, 40)
print(q)

[0.         0.16110732 0.32221463 0.48332195 0.64442926 0.80553658
 0.96664389 1.12775121 1.28885852 1.44996584 1.61107316 1.77218047
 1.93328779 2.0943951  2.25550242 2.41660973 2.57771705 2.73882436
 2.89993168 3.061039   3.22214631 3.38325363 3.54436094 3.70546826
 3.86657557 4.02768289 4.1887902  4.34989752 4.51100484 4.67211215
 4.83321947 4.99432678 5.1554341  5.31654141 5.47764873 5.63875604
 5.79986336 5.96097068 6.12207799 6.28318531]


In [44]:
s = np.sin(q)
print(s)

[ 0.00000000e+00  1.60411281e-01  3.16667994e-01  4.64723172e-01
  6.00742264e-01  7.21202447e-01  8.22983866e-01  9.03450435e-01
  9.60518112e-01  9.92708874e-01  9.99188998e-01  9.79790652e-01
  9.35016243e-01  8.66025404e-01  7.74604962e-01  6.63122658e-01
  5.34465826e-01  3.91966610e-01  2.39315664e-01  8.04665687e-02
 -8.04665687e-02 -2.39315664e-01 -3.91966610e-01 -5.34465826e-01
 -6.63122658e-01 -7.74604962e-01 -8.66025404e-01 -9.35016243e-01
 -9.79790652e-01 -9.99188998e-01 -9.92708874e-01 -9.60518112e-01
 -9.03450435e-01 -8.22983866e-01 -7.21202447e-01 -6.00742264e-01
 -4.64723172e-01 -3.16667994e-01 -1.60411281e-01 -2.44929360e-16]


In [45]:
j = np.zeros_like(o)
print(j)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [46]:
k = np.ones_like(game)
print(k)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [48]:
i = np.full((3, 3), 10)
print(i)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [49]:
l = np.full_like(i, 100)
print(l)

[[100 100 100]
 [100 100 100]
 [100 100 100]]


In [175]:
u = np.eye(3)
print(u)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [177]:
u = np.eye(4, dtype=int)
print(u)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


## Indexing, slicing, assigning to matrices

In [49]:
b[0, 1, 2]

6.0

In [50]:
a[2]

array([7, 8, 9])

In [51]:
b[1]

array([[ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [53]:
c[1] = 99

In [54]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[99, 99, 99],
        [99, 99, 99]]])

In [55]:
a[:, :2]

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [56]:
a[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
a[::2, ::2]

array([[1, 3],
       [7, 9]])

In [59]:
b[-1, -1, -1]

12.0

In [60]:
c[1, 1, 1] = 101
c

array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 99,  99,  99],
        [ 99, 101,  99]]])

In [63]:
a[0:3, 0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
a[range(0,3), range(0,3)]

array([1, 5, 9])

In [65]:
a[[range(0, 3)], [range(0,3)]]

array([[1, 5, 9]])

In [66]:
a[list(range(0, 3)), list(range(0,3))]

array([1, 5, 9])

In [69]:
a((0, 1, 2), (0, 1, 2)]

SyntaxError: invalid syntax (<ipython-input-69-4f986c985c0a>, line 1)

In [186]:
print(np.arange(1, 11, 2)[::-1])

[9 7 5 3 1]


## Summary statistics

In [70]:
a.sum

<function ndarray.sum>

In [71]:
a.sum()

78

In [74]:
a.sum(axis=0)

array([22, 26, 30])

In [73]:
a.sum(axis=1)

array([ 6, 15, 24, 33])

In [76]:
b.sum()

78.0

In [78]:
b.sum(axis=0)

array([[ 8., 10., 12.],
       [14., 16., 18.]], dtype=float32)

In [79]:
b.sum(axis=1)

array([[ 5.,  7.,  9.],
       [17., 19., 21.]], dtype=float32)

In [80]:
b.sum(axis=2)

array([[ 6., 15.],
       [24., 33.]], dtype=float32)

In [81]:
b.sum(axis=2).shape

(2, 2)

In [82]:
a.mean()

6.5

In [84]:
a.mean(axis=1)

array([ 2.,  5.,  8., 11.])

In [87]:
np.median(a, axis=1)

array([ 2.,  5.,  8., 11.])

In [88]:
a.median(axis=1)

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [89]:
b.stddev()

AttributeError: 'numpy.ndarray' object has no attribute 'stddev'

In [91]:
np.std(b)

3.4520526

In [92]:
b.std()

3.4520526

In [93]:
b.var()

11.916667

In [94]:
b.var(axis=0)

array([[9., 9., 9.],
       [9., 9., 9.]], dtype=float32)

In [57]:
print(a), print(a.cumsum(axis=0)), print(a.cumsum(axis=1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]
 [22 26 30]]
[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]
 [10 21 33]]


(None, None, None)

In [58]:
print(a.cumprod(axis=0)), print(a.cumprod(axis=1))

[[   1    2    3]
 [   4   10   18]
 [  28   80  162]
 [ 280  880 1944]]
[[   1    2    6]
 [   4   20  120]
 [   7   56  504]
 [  10  110 1320]]


(None, None)

## Broadcasting and Vectorized Operations

In [97]:
x = np.arange(10)

In [98]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
x + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [100]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
x += 10

In [102]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [103]:
x * 10

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [104]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [105]:
x = np.arange(10)
y = np.arange(10)

In [106]:
x, y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [107]:
x * y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [108]:
x + y

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [109]:
x, y

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [110]:
z = np.arange(5)

In [113]:
z

array([0, 1, 2, 3, 4])

In [114]:
x + z

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [115]:
w = np.arange(10)

In [119]:
w = w.reshape(10, 1)

In [120]:
x * w

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [121]:
x, w

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]]))

In [144]:
w * x

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [122]:
z = z.reshape(5, 1)

In [123]:
z

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [124]:
x * z

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36]])

In [126]:
x + w

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [127]:
x + z

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13]])

In [160]:
x.shape, y.shape, z.shape, w.shape

((10,), (10,), (5, 1), (10, 1))

The above operations work even though dimensions of x are (1, 10) and dimensions of w and z are (10, 1) and (5, 1) respectively. However, it works for w and z because w and z have only one column. If instead, they had two columns, these operations would give value error even if one dimesion matches. This is shown below for x and g.

In [128]:
x + a

ValueError: operands could not be broadcast together with shapes (10,) (4,3) 

In [150]:
f = np.array([[i for i in range(10)], [i*10 for i in range(10)]])

In [151]:
f

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]])

In [152]:
x + f

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99]])

In [153]:
x * f

array([[  0,   1,   4,   9,  16,  25,  36,  49,  64,  81],
       [  0,  10,  40,  90, 160, 250, 360, 490, 640, 810]])

In [154]:
g = f.transpose() 

In [155]:
g

array([[ 0,  0],
       [ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40],
       [ 5, 50],
       [ 6, 60],
       [ 7, 70],
       [ 8, 80],
       [ 9, 90]])

In [156]:
x + g

ValueError: operands could not be broadcast together with shapes (10,) (10,2) 

In [157]:
x * g

ValueError: operands could not be broadcast together with shapes (10,) (10,2) 

## Boolean Arrays

In [164]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [163]:
a[[True, False, True], [False, True, False], [True, False, True]]

IndexError: too many indices for array

In [167]:
a[np.array([[True, False, True], [False, True, False], [True, False, True], [False, True, False]])]

array([ 1,  3,  5,  7,  9, 11])

In [169]:
a[a > 5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [171]:
a[a > a.mean()]

array([ 7,  8,  9, 10, 11, 12])

In [178]:
a[~(a > a.mean())]

array([1, 2, 3, 4, 5, 6])

In [176]:
a[(a > a.mean()) | (a % 2 == 0)]

array([ 2,  4,  6,  7,  8,  9, 10, 11, 12])

In [177]:
a[(a > a.mean()) & (a % 2 == 0)]

array([ 8, 10, 12])

In [180]:
diag = np.eye(3, dtype=bool)
print(diag)

[[ True False False]
 [False  True False]
 [False False  True]]


## Linear Algebra

In [179]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [180]:
a.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [182]:
m = np.array([[1, 1], [1, 1], [1, 1]])

In [183]:
a.dot(m)

array([[ 6,  6],
       [15, 15],
       [24, 24],
       [33, 33]])

In [184]:
a @ m

array([[ 6,  6],
       [15, 15],
       [24, 24],
       [33, 33]])

In [185]:
n = np.array([[1, 1, 1, 1], [1, 1, 1, 1], [1, 1, 1, 1]])

In [186]:
n.shape

(3, 4)

In [187]:
n.T

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [188]:
a.T @ n.T

array([[22, 22, 22],
       [26, 26, 26],
       [30, 30, 30]])

There are many other linear algebra functions like corrcoef, cov, cross

## Size and Performanace

In [190]:
import sys

In [192]:
sys.getsizeof(1)

28

In [194]:
np.dtype(np.int8).itemsize

1

In [195]:
np.dtype(float).itemsize

8

In [193]:
sys.getsizeof([1])

72

In [196]:
np.array([1]).nbytes

8

In [203]:
num = 10000

In [204]:
l = list(range(num))

In [205]:
%time sum([x ** 2 for x in l])

CPU times: user 1.9 ms, sys: 0 ns, total: 1.9 ms
Wall time: 1.91 ms


333283335000

In [206]:
r = np.arange(num)

In [207]:
%time np.sum(r ** 2)

CPU times: user 576 µs, sys: 0 ns, total: 576 µs
Wall time: 416 µs


333283335000

## Random Sampling
The seed given to default_rng decides the sequence. For the same seed, same numbers are generated.

In [84]:
rg = np.random.default_rng(1)

In [88]:
print(rg.integers(10, size=(2,3)))

[[0 0 8]
 [7 8 5]]


In [65]:
print(rg.random(size=(3,4)))

[[0.94864945 0.31183145 0.42332645 0.82770259]
 [0.40919914 0.54959369 0.02755911 0.75351311]
 [0.53814331 0.32973172 0.7884287  0.30319483]]


In [93]:
rg = np.random.Generator(np.random.MT19937(4546723))
print(rg.random(4))

[0.17991083 0.27557075 0.93344448 0.79169144]


In [95]:
rg = np.random.Generator(np.random.PCG64(45723))
print(rg.standard_normal(10))

[ 0.9765373   1.58263087  1.0273624   0.52308944 -1.7163116   0.88719672
 -2.466767    0.85296146 -0.72800473 -1.98516051]


In [99]:
rg = np.random.default_rng(4546111)
print(rg.poisson(10, 10))

[12 11 12  8  8 14 11  9 12  6]


## Universal Functions

In [105]:
a = [[1, 1, 1],
    [2, 0, 2],
    [3, 0, 3]]
np.all(a, axis=0)

array([ True, False,  True])

In [106]:
np.all(a, axis=1)

array([ True, False, False])

In [107]:
np.any([1, 0, 0])

True

In [108]:
np.any([0, 0, 0])

False

In [110]:
game = [[1, 0, 2],
        [2, 1, 2],
        [1, 1, 2]]
np.apply_along_axis(np.sum, axis=0, arr=game)

array([4, 2, 6])

In [111]:
b = np.arange(24).reshape(2,3,4)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [112]:
np.apply_over_axes(np.sum, b, [1,2])

array([[[ 66]],

       [[210]]])

In [113]:
np.argmax(game, axis=0)

array([1, 1, 0])

In [114]:
np.argmin(game, axis=1)

array([1, 1, 0])

In [115]:
np.argsort(game)

array([[1, 0, 2],
       [1, 0, 2],
       [0, 1, 2]])

Default axis is 1 in the above example

In [117]:
np.argsort(game, axis=0)

array([[0, 0, 0],
       [2, 1, 1],
       [1, 2, 2]])

In [118]:
np.bincount(np.array([3, 4, 3, 4, 2, 1, 11, 1, 1, 1, 1, 0, 0, 0, 4, 3, 5]))

array([3, 5, 1, 3, 3, 1, 0, 0, 0, 0, 0, 1])

## Copies and views

In [141]:
rg = np.random.default_rng(19)
a = rg.integers(20, size=(2, 4))

In [142]:
a

array([[11,  8,  7, 18],
       [ 7,  5, 17,  1]])

### No copy

In [143]:
b = a

In [144]:
id(a)

139751690897648

In [145]:
id(b)

139751690897648

In [146]:
b is a

True

### Shallow copy

In [147]:
c = a.view()

In [148]:
id(c)

139751691261872

In [149]:
c is a

False

In [150]:
c.base is a

True

In [151]:
c.base

array([[11,  8,  7, 18],
       [ 7,  5, 17,  1]])

In [155]:
c = c.reshape(4, 2)
print(c)

[[11  8]
 [ 7 18]
 [ 7  5]
 [17  1]]


In [156]:
a.shape

(2, 4)

In [157]:
c[0, 0] = 100

In [159]:
print(c)

[[100   8]
 [  7  18]
 [  7   5]
 [ 17   1]]


In [160]:
print(a)

[[100   8   7  18]
 [  7   5  17   1]]


In [164]:
d = a[:, 2:4]
print(d)

[[ 7 18]
 [17  1]]


In [166]:
d[:] = 10

In [167]:
print(a)

[[100   8  10  10]
 [  7   5  10  10]]


### Deep copy

In [169]:
e = a.copy()
print(e)

[[100   8  10  10]
 [  7   5  10  10]]


In [170]:
e is a

False

In [171]:
e.base is a

False

In [172]:
id(e)

139751690906000

In [173]:
e[0, 0] = 999
print(e)

[[999   8  10  10]
 [  7   5  10  10]]


In [174]:
print(a)

[[100   8  10  10]
 [  7   5  10  10]]
